// Hyperion — static-site export of the wiki vault (M4, Requirements #13, #16).
//
// Turns the on-disk wiki collection (`hyperion/docs/wiki/*.html`) into a
// self-contained folder the operator can hand off, host, or archive: every page
// is copied verbatim and a generated `index.html` gallery links them all. The
// core is a pure function over (slug, title, html) tuples plus a destination
// directory — no network, no DB, no global state — so it unit-tests cleanly into
// a temp dir. A thin gather helper (used by the Tauri command, not the pure fn)
// reads the pages off disk. Strictly read-only with respect to bOS data.

use std::fs;
use std::path::{Path, PathBuf};

use serde::Serialize;

/// Result of an export: how many content pages were written and the absolute
/// path of the generated gallery `index.html`. Serializes to a flat JSON object
/// the webview can show directly.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct ExportSummary {
    pub written: usize,
    pub index_path: String,
}

/// Validate a page slug so it can only ever name a single `.html` file directly
/// inside `dest` — never escape it via `..`, an absolute path, or a separator.
/// Allows the conservative filename alphabet the wiki uses (`a-z A-Z 0-9 _ -`).
fn safe_slug(slug: &str) -> Result<&str, String> {
    let s = slug.trim();
    if s.is_empty() {
        return Err("empty page slug".into());
    }
    if s.eq_ignore_ascii_case("index") {
        return Err("page slug 'index' is reserved for the gallery".into());
    }
    if !s
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        return Err(format!("unsafe page slug: {slug:?}"));
    }
    Ok(s)
}

/// Minimal HTML-text escaping for values spliced into the generated gallery
/// (page titles). Keeps a hostile/odd title from breaking the index markup.
fn escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// Export `pages` into `dest`: write each as `dest/<slug>.html` (verbatim) and a
/// generated `dest/index.html` linking them in the given order. Pure over its
/// inputs and the destination dir — no network, no DB. Returns the count of
/// content pages written (the gallery index is not counted) and the index path.
///
/// `dest` is created if missing. Slugs are validated (see `safe_slug`) so a page
/// can only ever land directly inside `dest`; an invalid slug fails the whole
/// export rather than writing a partial, surprising tree.
pub fn export_site(
    pages: &[(String, String, String)],
    dest: &Path,
) -> Result<ExportSummary, String> {
    fs::create_dir_all(dest).map_err(|e| format!("create export dir: {e}"))?;

    // Validate every slug up front so we don't write half a site before noticing
    // a bad one, and reject duplicates (two pages fighting over one file).
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    for (slug, _, _) in pages {
        let s = safe_slug(slug)?;
        if !seen.insert(s.to_ascii_lowercase()) {
            return Err(format!("duplicate page slug: {s:?}"));
        }
    }

    let mut items = String::new();
    for (slug, title, html) in pages {
        let s = safe_slug(slug)?; // already validated; re-check keeps `s` borrow-local
        let file = dest.join(format!("{s}.html"));
        fs::write(&file, html).map_err(|e| format!("write {}: {e}", file.display()))?;
        let label = if title.trim().is_empty() {
            s.to_string()
        } else {
            title.trim().to_string()
        };
        items.push_str(&format!(
            "      <li><a class=\"card\" href=\"{href}\"><span class=\"slug\">{slug_disp}</span>{label}</a></li>\n",
            href = escape(&format!("{s}.html")),
            slug_disp = escape(s),
            label = escape(&label),
        ));
    }

    let index_html = render_index(&items, pages.len());
    let index_path = dest.join("index.html");
    fs::write(&index_path, index_html)
        .map_err(|e| format!("write {}: {e}", index_path.display()))?;

    Ok(ExportSummary {
        written: pages.len(),
        index_path: index_path.to_string_lossy().into_owned(),
    })
}

/// The generated gallery page. Self-contained and themeable via `:root` tokens,
/// matching the visual language of the hand-authored wiki pages it links.
fn render_index(items: &str, count: usize) -> String {
    let noun = if count == 1 { "page" } else { "pages" };
    format!(
        "<!doctype html>\n\
<html lang=\"en\">\n\
<head>\n\
<meta charset=\"utf-8\">\n\
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
<title>Hyperion Wiki — Exported Site</title>\n\
<!-- Generated by Hyperion static-site export (M4). Themeable via :root tokens. -->\n\
<style>\n\
  :root{{\n\
    --bg:#f4f6f8; --pan:#ffffff; --ink:#1f2a36; --mut:#67788a; --line:#dce3ea;\n\
    --acc:#2b6cb0; --acc-soft:#e8f1fb; --radius:10px;\n\
    --sans:system-ui,-apple-system,\"Segoe UI\",Roboto,sans-serif;\n\
    --mono:Consolas,ui-monospace,\"SFMono-Regular\",monospace;\n\
  }}\n\
  *{{box-sizing:border-box}}\n\
  body{{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}}\n\
  .wrap{{max-width:960px;margin:0 auto;padding:40px 22px 80px}}\n\
  .kicker{{font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:var(--acc);font-weight:600}}\n\
  h1{{font-size:32px;margin:.18em 0 .1em}}\n\
  .lede{{font-size:17px;color:var(--mut);max-width:62ch}}\n\
  ul.grid{{list-style:none;margin:28px 0 0;padding:0;display:grid;\n\
    grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:14px}}\n\
  .card{{display:block;text-decoration:none;color:inherit;background:var(--pan);\n\
    border:1px solid var(--line);border-radius:var(--radius);padding:16px 18px;\n\
    transition:border-color .15s,box-shadow .15s}}\n\
  .card:hover{{border-color:var(--acc);box-shadow:0 2px 10px rgba(20,60,110,.08)}}\n\
  .card .slug{{display:block;font-family:var(--mono);font-size:11px;color:var(--acc);margin-bottom:4px}}\n\
  .foot{{margin-top:44px;border-top:1px solid var(--line);padding-top:14px;color:var(--mut);font-size:13px}}\n\
</style>\n\
</head>\n\
<body>\n\
<div class=\"wrap\">\n\
  <div class=\"kicker\">Hyperion · exported wiki vault</div>\n\
  <h1>Project Wiki</h1>\n\
  <p class=\"lede\">A self-contained static export of the documentation vault. {count} {noun},\n\
    each a standalone HTML document you can host, archive, or hand off as-is.</p>\n\
  <nav aria-label=\"Wiki pages\">\n\
    <ul class=\"grid\">\n\
{items}    </ul>\n\
  </nav>\n\
  <p class=\"foot\">Generated by Hyperion · static-site export. No external assets, no network.</p>\n\
</div>\n\
</body>\n\
</html>\n"
    )
}

/// Extract the human title of a wiki page from its `<title>…</title>`, trimming
/// any " · Hyperion Wiki" suffix and decoding the few entities the pages use.
/// Returns `None` when there is no usable title (callers fall back to the slug).
fn extract_title(html: &str) -> Option<String> {
    let lower = html.to_ascii_lowercase();
    let open = lower.find("<title")?;
    let gt = lower[open..].find('>')? + open + 1;
    let close = lower[gt..].find("</title>")? + gt;
    let raw = html[gt..close].trim();
    if raw.is_empty() {
        return None;
    }
    // Pages title as "Feature Name · Hyperion Wiki"; keep just the feature name.
    let trimmed = raw.split(" · ").next().unwrap_or(raw).trim();
    let decoded = trimmed
        .replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"");
    let decoded = decoded.trim();
    if decoded.is_empty() {
        None
    } else {
        Some(decoded.to_string())
    }
}

/// Gather the wiki pages from an on-disk directory of `*.html` files, as
/// `(slug, title, html)` tuples sorted by slug. The slug is the file stem; the
/// title comes from the page's `<title>` (falling back to the slug). Any
/// `index.html` is skipped — the export generates its own gallery index.
///
/// Used by the `wiki_export` command; the pure `export_site` takes the tuples
/// directly so it needs no filesystem layout to test.
pub fn gather_wiki_pages(wiki_dir: &Path) -> Result<Vec<(String, String, String)>, String> {
    let rd =
        fs::read_dir(wiki_dir).map_err(|e| format!("read wiki dir {}: {e}", wiki_dir.display()))?;

    let mut paths: Vec<PathBuf> = Vec::new();
    for entry in rd {
        let entry = entry.map_err(|e| format!("read wiki dir entry: {e}"))?;
        let path = entry.path();
        let is_html = path
            .extension()
            .and_then(|e| e.to_str())
            .map(|e| e.eq_ignore_ascii_case("html"))
            .unwrap_or(false);
        if is_html && path.is_file() {
            paths.push(path);
        }
    }
    // Deterministic order regardless of directory iteration order.
    paths.sort();

    let mut pages = Vec::new();
    for path in paths {
        let stem = match path.file_stem().and_then(|s| s.to_str()) {
            Some(s) => s.to_string(),
            None => continue,
        };
        // The generated gallery owns `index.html`; skip any hand-authored landing
        // page so it can't collide with (or be shadowed by) the export's index.
        if stem.eq_ignore_ascii_case("index") {
            continue;
        }
        // Skip slugs we couldn't safely write back out, rather than failing the
        // whole export over one oddly named file.
        if safe_slug(&stem).is_err() {
            continue;
        }
        let html =
            fs::read_to_string(&path).map_err(|e| format!("read {}: {e}", path.display()))?;
        let title = extract_title(&html).unwrap_or_else(|| stem.clone());
        pages.push((stem, title, html));
    }
    Ok(pages)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// A fresh, empty directory under the OS temp dir; returns its path.
    fn fresh_dir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "hyperion_export_test_{}_{}",
            std::process::id(),
            tag
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn synthetic_pages() -> Vec<(String, String, String)> {
        vec![
            (
                "alpha".into(),
                "Alpha Feature".into(),
                "<!doctype html><title>Alpha</title><h1>Alpha</h1>".into(),
            ),
            (
                "beta-two".into(),
                "Beta & Two".into(),
                "<!doctype html><title>Beta</title><h1>Beta</h1>".into(),
            ),
        ]
    }

    #[test]
    fn export_writes_pages_and_index() {
        let dest = fresh_dir("write");
        let pages = synthetic_pages();
        let summary = export_site(&pages, &dest).unwrap();

        assert_eq!(summary.written, 2);
        assert!(dest.join("alpha.html").is_file());
        assert!(dest.join("beta-two.html").is_file());

        let index_path = PathBuf::from(&summary.index_path);
        assert!(index_path.is_file());
        assert_eq!(index_path, dest.join("index.html"));

        // Each content page is copied verbatim.
        assert_eq!(
            std::fs::read_to_string(dest.join("alpha.html")).unwrap(),
            pages[0].2
        );

        // The gallery links each page and HTML-escapes the title.
        let index = std::fs::read_to_string(&index_path).unwrap();
        assert!(index.contains("href=\"alpha.html\""));
        assert!(index.contains("href=\"beta-two.html\""));
        assert!(index.contains("Beta &amp; Two"));
        assert!(index.contains("2 pages"));

        let _ = std::fs::remove_dir_all(&dest);
    }

    #[test]
    fn export_creates_missing_dest_dir() {
        let base = fresh_dir("nested");
        let dest = base.join("a").join("b"); // does not exist yet
        let summary = export_site(&synthetic_pages(), &dest).unwrap();
        assert_eq!(summary.written, 2);
        assert!(dest.join("index.html").is_file());
        let _ = std::fs::remove_dir_all(&base);
    }

    #[test]
    fn export_rejects_unsafe_and_reserved_slugs() {
        let dest = fresh_dir("unsafe");
        let traversal = vec![("../evil".into(), "Evil".into(), "<h1>nope</h1>".into())];
        assert!(export_site(&traversal, &dest).is_err());
        // Nothing should have been written outside dest.
        assert!(!dest.parent().unwrap().join("evil.html").exists());

        let reserved = vec![("index".into(), "Clash".into(), "<h1>x</h1>".into())];
        assert!(export_site(&reserved, &dest).is_err());

        let _ = std::fs::remove_dir_all(&dest);
    }

    #[test]
    fn export_rejects_duplicate_slugs() {
        let dest = fresh_dir("dupe");
        let dupes = vec![
            ("same".into(), "One".into(), "<h1>1</h1>".into()),
            ("same".into(), "Two".into(), "<h1>2</h1>".into()),
        ];
        assert!(export_site(&dupes, &dest).is_err());
        let _ = std::fs::remove_dir_all(&dest);
    }

    #[test]
    fn gather_reads_pages_and_skips_index() {
        let wiki = fresh_dir("gather");
        std::fs::write(
            wiki.join("agent.html"),
            "<title>The Agent &amp; Runtime · Hyperion Wiki</title><h1>Agent</h1>",
        )
        .unwrap();
        std::fs::write(
            wiki.join("vault.html"),
            "<title>Vault · Hyperion Wiki</title><h1>Vault</h1>",
        )
        .unwrap();
        std::fs::write(wiki.join("index.html"), "<title>Wiki</title>").unwrap();
        std::fs::write(wiki.join("notes.txt"), "ignored").unwrap();

        let pages = gather_wiki_pages(&wiki).unwrap();
        let slugs: Vec<&str> = pages.iter().map(|(s, _, _)| s.as_str()).collect();
        assert_eq!(slugs, vec!["agent", "vault"]); // sorted, no index/non-html

        // Title is extracted from <title> with the " · Hyperion Wiki" suffix
        // trimmed and the &amp; entity decoded.
        assert_eq!(pages[0].1, "The Agent & Runtime");
        assert_eq!(pages[1].1, "Vault");

        // End-to-end: gathered pages export cleanly.
        let dest = fresh_dir("gather_out");
        let summary = export_site(&pages, &dest).unwrap();
        assert_eq!(summary.written, 2);
        assert!(dest.join("agent.html").is_file());

        let _ = std::fs::remove_dir_all(&wiki);
        let _ = std::fs::remove_dir_all(&dest);
    }

    #[test]
    fn extract_title_falls_back_when_absent() {
        assert_eq!(extract_title("<h1>no title here</h1>"), None);
        assert_eq!(extract_title("<title>   </title>"), None);
        assert_eq!(
            extract_title("<title>Just A Title</title>").as_deref(),
            Some("Just A Title")
        );
    }
}
